// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Insertable, Selectable, Updateable } from "kysely";

/** Identifier type for public.car */
export type CarId = string & { __brand: "public.car" };

/** Represents the table public.car */
export default interface CarTable {
	id: ColumnType<CarId, CarId | undefined, CarId>;

	created_at: ColumnType<Date, Date | string | undefined, Date | string>;

	brand_name: ColumnType<string, string, string>;

	model_name: ColumnType<string, string, string>;

	year: ColumnType<string, string, string>;

	color: ColumnType<string, string, string>;
}

export type Car = Selectable<CarTable>;

export type NewCar = Insertable<CarTable>;

export type CarUpdate = Updateable<CarTable>;
