// @generated
// This file is automatically generated by Kanel. Do not modify manually.

export interface generate_ulid_params {
	prefix: string;
}

/** Return type for generate_ulid */
export type generate_ulid_return_type = string;
