// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as CarTable } from "./Car";
import type { default as KyselyMigrationTable } from "./KyselyMigration";
import type { default as KyselyMigrationLockTable } from "./KyselyMigrationLock";

export default interface PublicSchema {
	kysely_migration_lock: KyselyMigrationLockTable;

	car: CarTable;

	kysely_migration: KyselyMigrationTable;
}
